# Generated by Django 6.1.1 on 2026-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('categoria', models.CharField(choices=[('backend', 'Back-end'), ('frontend', 'Front-end'), ('dados', 'Dados e banco'), ('ferramentas', 'Ferramentas e DevOps')], default='backend', max_length=20, verbose_name='categoria')),
                ('nivel', models.PositiveSmallIntegerField(default=60, help_text='Uso esse número para desenhar a barra de progresso.', verbose_name='nível (0 a 100)')),
                ('descricao', models.CharField(blank=True, max_length=160, verbose_name='descrição curta')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem de exibição')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque')),
            ],
            options={
                'verbose_name': 'habilidade',
                'verbose_name_plural': 'habilidades',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('assunto', models.CharField(blank=True, max_length=140, verbose_name='assunto')),
                ('conteudo', models.TextField(verbose_name='mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome completo')),
                ('titulo', models.CharField(help_text='Ex.: Desenvolvedor Full Stack | Analista e Desenvolvedor de Sistemas', max_length=140, verbose_name='título profissional')),
                ('resumo', models.TextField(help_text='Frase de impacto que aparece no topo da página (hero).', verbose_name='resumo curto')),
                ('bio', models.TextField(help_text="Texto da seção 'Sobre mim'. Cada linha em branco vira um parágrafo.", verbose_name='biografia')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail de contato')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone/WhatsApp')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('curriculo', models.URLField(blank=True, verbose_name='link do currículo')),
                ('disponivel', models.BooleanField(default=True, help_text='Controla o selo verde de disponibilidade no topo do site.', verbose_name='disponível para novos projetos')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='título')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título se eu deixar em branco.', max_length=160, unique=True, verbose_name='slug')),
                ('resumo', models.CharField(help_text='Uma linha, aparece no card.', max_length=220, verbose_name='resumo')),
                ('descricao', models.TextField(help_text='Texto da página de detalhe do projeto.', verbose_name='descrição completa')),
                ('linguagem', models.CharField(blank=True, max_length=40, verbose_name='linguagem principal')),
                ('tecnologias', models.CharField(blank=True, help_text='Separadas por vírgula. Ex.: Django, PostgreSQL, HTML', max_length=200, verbose_name='tecnologias')),
                ('repositorio', models.URLField(blank=True, verbose_name='link do repositório')),
                ('demo', models.URLField(blank=True, verbose_name='link do site publicado')),
                ('ano', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ano')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='ordem de exibição')),
                ('publicado', models.BooleanField(default=True, verbose_name='publicado')),
                ('destaque', models.BooleanField(default=False, help_text='Aparece na vitrine da página inicial.', verbose_name='destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['ordem', '-ano', 'titulo'],
                'indexes': [models.Index(fields=['publicado', 'destaque'], name='portfolio_p_publica_d0b90a_idx')],
            },
        ),
    ]
